---
- hosts: clients
  become: true
  tasks:
   - name: Install MySQL
     apt : name={{ item }} state=present
     with_items:
       - mysql-server
       - python-mysqldb

   - name: Turn on mysql and run
     service: name={{ item }} state=started enabled=yes
     with_items:
       - mysql

   - name: create a test database
     mysql_db: name=testDb
               state=present

   - name: create a new user for connections
     mysql_user: name=webapp
                 password=admin123
                 priv=*.*:ALL state=present
